# Generated by Django 5.2.6 on 2025-09-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='student_management.addoncourse'),
        ),
    ]
