# Generated by Django 5.2.6 on 2025-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_coursepurchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchaserequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepurchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'In Progress'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
