# Generated by Django 5.2.6 on 2025-09-26 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18.')]),
        ),
    ]
